version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest:v11.1.0
    ports:
      - "3001:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:app_password@db:5432/app
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user
      PGRST_JWT_SECRET: testkeydonotuseinproductionorelse
      PGRST_JWT_AUD: messaging_app
      PGRST_JWT_ROLE_CLAIM_KEY: ".role"
    depends_on:
      - db

volumes:
  postgres-data: 